"""restructure notes to day-lesson-note

Revision ID: 4b8807be0583
Revises: 5ef7a8b5f6ce
Create Date: 2026-01-13 17:50:17.152824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8807be0583'
down_revision = '5ef7a8b5f6ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_note_lesson_id', 'lesson', ['lesson_id'], ['id'])
        batch_op.drop_column('topic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_constraint('fk_note_lesson_id', type_='foreignkey')
        batch_op.drop_column('lesson_id')

    op.drop_table('lesson')
    op.drop_table('day')
    # ### end Alembic commands ###
