"""Increase profile_pic column size to 255

Revision ID: 82051c7981c6
Revises: 8881c99c9136
Create Date: 2026-01-15 14:21:06.070907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82051c7981c6'
down_revision = '8881c99c9136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_pic',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_pic',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
